export const WORLD_GRID_COLUMNS = 10;
export const WORLD_GRID_ROWS = 14;
export const WORLD_COOLDOWN_SECONDS = 10;
export const IMPRESSION_UNLOCK_THRESHOLD = 72;
export const IMPRESSION_EVALUATION_INTERVAL = 5;
export const KA_MESSAGES_PER_CONVERSATION = 10;
export const OFFLINE_MAX_CONVERSATIONS_PER_DAY = 10;
export const OFFLINE_MAX_MESSAGES_PER_CONVERSATION = 20;
