#!/usr/bin/env python3
"""
Analyze the map_aaru.png image to detect obstacle cells by pixel color.

Image: 1536x1024, cell size: 16x16 → 96 columns × 64 rows.
SpriteKit y-axis is flipped: image row 0 (top) = SpriteKit row 63.

Obstacle classification by average cell color:
  - Water (blue): blocked
  - Dense forest (dark green): blocked
  - Buildings/temples (structured brown/gray): blocked
  - Sand, grass with scattered vegetation: walkable

Output: src/domain/obstacle_map.ts
"""

from PIL import Image
import statistics

MAP_PATH = "/Users/tianzhichen/projects/aaru/AARU/Resources/Environment/sunset_beach_map.png"
OUT_PATH = "/Users/tianzhichen/projects/aaru/src/domain/obstacle_map.ts"

CELL = 16
img = Image.open(MAP_PATH).convert("RGB")
W, H = img.size
COLS = W // CELL  # 96
ROWS = H // CELL  # 64

print(f"Image: {W}x{H}, Grid: {COLS}x{ROWS}, Total cells: {COLS*ROWS}")

pixels = img.load()
blocked = set()

for img_row in range(ROWS):
    for col in range(COLS):
        # Sample all pixels in this 16x16 cell
        rs, gs, bs = [], [], []
        for py in range(img_row * CELL, (img_row + 1) * CELL):
            for px in range(col * CELL, (col + 1) * CELL):
                r, g, b = pixels[px, py]
                rs.append(r)
                gs.append(g)
                bs.append(b)

        avg_r = statistics.mean(rs)
        avg_g = statistics.mean(gs)
        avg_b = statistics.mean(bs)

        # SpriteKit row (y=0 at bottom)
        sk_row = (ROWS - 1) - img_row

        # Classification
        is_water = (avg_b > 130 and avg_b > avg_r + 20 and avg_r < 130)
        is_dense_forest = (avg_g > 120 and avg_r < 85 and avg_b < 90)
        is_dark_vegetation = (avg_g > 100 and avg_r < 80 and avg_b < 80)

        # Buildings: brownish-gray structures, detect by medium values
        # Temples have golden/brown tones with higher R than surrounds
        # We'll be conservative here - mainly block water and dense forest
        is_building = False
        # Buildings tend to have structured patterns with avg_r 140-190, avg_g 120-160, avg_b 80-120
        # and are in specific areas (temples, gates)
        # A simple heuristic: if it's not sand, not water, not forest, and has specific tones
        if (120 < avg_r < 175 and 100 < avg_g < 145 and 60 < avg_b < 110
                and abs(avg_r - avg_g) < 40 and avg_r > avg_b):
            # This catches stone/building-like colors
            # But also catches some sandy areas, so add stricter checks
            if avg_g < 130 and avg_r < 160:
                is_building = True

        if is_water or is_dense_forest or is_dark_vegetation:
            blocked.add((col, sk_row))

# Count stats
water_count = 0
forest_count = 0
other_blocked = 0
for img_row in range(ROWS):
    for col in range(COLS):
        sk_row = (ROWS - 1) - img_row
        if (col, sk_row) not in blocked:
            continue
        rs, gs, bs = [], [], []
        for py in range(img_row * CELL, (img_row + 1) * CELL):
            for px in range(col * CELL, (col + 1) * CELL):
                r, g, b = pixels[px, py]
                rs.append(r)
                gs.append(g)
                bs.append(b)
        avg_r = statistics.mean(rs)
        avg_g = statistics.mean(gs)
        avg_b = statistics.mean(bs)
        if avg_b > 130 and avg_b > avg_r + 20 and avg_r < 130:
            water_count += 1
        elif avg_g > 100 and avg_r < 85:
            forest_count += 1
        else:
            other_blocked += 1

total = COLS * ROWS
walkable = total - len(blocked)
pct_blocked = len(blocked) / total * 100

print(f"Water cells: {water_count}")
print(f"Forest cells: {forest_count}")
print(f"Other blocked: {other_blocked}")
print(f"Total blocked: {len(blocked)}/{total} ({pct_blocked:.1f}%)")
print(f"Walkable: {walkable} ({walkable/total*100:.1f}%)")

# Export
blocked_list = sorted(f"{c}:{r}" for c, r in blocked)
ts_code = f'''// Auto-generated by scripts/analyze_map_obstacles.py — do not edit manually
// Map: {COLS}x{ROWS} grid ({CELL}px cells), {len(blocked_list)} blocked cells ({pct_blocked:.1f}%)
export const OBSTACLE_CELLS: ReadonlySet<string> = new Set([
{",".join(f'"{k}"' for k in blocked_list)}
]);
'''
with open(OUT_PATH, "w") as f:
    f.write(ts_code)
print(f"Wrote {OUT_PATH}")
