main = "src/index.ts"
compatibility_date = "2024-12-01"
name = "thumos-api"

[observability]
enabled = true

[env.dev]
name = "thumos-api-dev"
workers_dev = true

[[env.dev.queues.producers]]
binding = "BACKGROUND_QUEUE"
queue = "thumos-soul-synthesis-dev"

[[env.dev.queues.consumers]]
queue = "thumos-soul-synthesis-dev"
max_batch_size = 50

[env.dev.triggers]
crons = ["0 6 * * *"]

[env.production]
name = "thumos-api"
workers_dev = false
routes = [{ pattern = "api.trymagpie.xyz/*", zone_name = "trymagpie.xyz" }]

[[env.production.queues.producers]]
binding = "BACKGROUND_QUEUE"
queue = "thumos-soul-synthesis"

[[env.production.queues.consumers]]
queue = "thumos-soul-synthesis"
max_batch_size = 50

[env.production.triggers]
crons = ["0 6 * * *"]
